### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by JackPlaysGames0510** [iCrazeiOS/YTETA#1]
This crashes on 18.43.4

**Comment by iCrazeiOS** [comment]
just pushed a new version to my repo. please give it a go

**Comment by JackPlaysGames0510** [comment]
Ok will do

**Comment by JackPlaysGames0510** [comment]
Still crashes

**Comment by JackPlaysGames0510** [comment]
It might be a confrontation I will of what though

**Comment by iCrazeiOS** [comment]
do you have a crash log? I feel it may be caused by some youtube a/b testing thing

**Comment by iCrazeiOS** [comment]
my youtube app just started crashing, and it is caused by uYou. do you have uyou?

**Comment by JackPlaysGames0510** [comment]
No I use ytlight and ab config

**Comment by JackPlaysGames0510** [comment]
Remind me how do I get the crash log

**Comment by JackPlaysGames0510** [comment]
[YouTube-2023-10-30-091508.ips.zip](https://github.com/iCrazeiOS/YTETA/files/13212112/YouTube-2023-10-30-091508.ips.zip)
[YouTube.wakeups_resource-2023-10-30-214648.ips.zip](https://github.com/iCrazeiOS/YTETA/files/13212113/YouTube.wakeups_resource-2023-10-30-214648.ips.zip)

**Comment by iCrazeiOS** [comment]
Do you have choicy? try disabling all tweak injection into youtuber, except YTETA

**Comment by JackPlaysGames0510** [comment]
I just did and it still crashes but I sideload the tweak I don’t have a jailbreak iPhone and the 1.3.1 tweak did work

**Comment by iCrazeiOS** [comment]
finally reproduced the crash

new build should be on the repo now

some other tweaks also seem broken, but YTETA definitely works now

**Comment by JackPlaysGames0510** [comment]
Yeah I’ve noticed that YTHoldForSpeed doesn’t work as well I will have a look

**Comment by iCrazeiOS** [comment]
my uYouCrashFix tweak may also fix YTHoldForSpeed - the YT update changed some things related to speed control (which is what broke YTETA and uYou)

**Comment by JackPlaysGames0510** [comment]
Oh right I see I will have a look I noticed the YTETA doesn’t stay on the screen

**Comment by JackPlaysGames0510** [comment]
Also uYouCrashFix did fix YTHoldSpeed thanks for that
